# Should be set by init-dot-files.sh 
# If #setme# is still here, either run the script or change this manually
DOT_FILES_PROJECT_DIRECTORY=/Users/djtjwillia/Code/dogfiles
#omzsh
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME=""
plugins=(git aws docker iiterm2 terraform python kubectl)
source $ZSH/oh-my-zsh.sh

# source all global variables
for f in $DOT_FILES_PROJECT_DIRECTORY/globals/*; do source "$f"; done;
# source all functions
for f in $DOT_FILES_PROJECT_DIRECTORY/fuunctions/*; do source "$f"; done;
# souorce all aliases
for f in $DOT_FILES_PROJECT_DIRECTORY/aliases/*; do source "$f"; done;