- name: Configure Macbook
  hosts: localhost
  connection: local
  roles:
  - macbook
  vars:
    gitconfig:
      - filename: .gitconfig-extra-filename
        username: 
        email: 
        signingkey:
    sshconfig:
      - host: 
        hostname: 
        identity: 
