- name: Create .zshrc
  template:
    src: ../templates/zshrc.j2
    dest: ~/.zshrc

- name: Check for SSH folder
  stat:
    path: ~/.ssh
  register: ssh

- name: Create SSH folder
  when: not ssh.stat.exists
  file:
    path: ~/.ssh
    state: directory

- name: Setup SSH Config
  template:
    src: ../templates/ssh_config.j2
    dest: ~/.ssh/config

- name: Setup gitconfig
  copy:
    src: ../files/gitconfig
    dest: ~/.gitconfig

- name: Setup Other Git Configs
  template:
    src: ../templates/gitconfig-template.j2
    dest: "~/{{ item.filename }}"
  with_items: "{{ gitconfig }}"

- name: Check for dotfiles folder
  stat:
    path: ~/.dotfiles
  register: dotfiles

- name: Create dotfiles folder
  when: not dotfiles.stat.exists
  file:
    path: ~/.dotfiles
    state: directory

- name: Move aliases into dotfiles
  copy:
    src: ../files/aliases
    dest: ~/.dotfiles/aliases

- name: Move functions into dotfiles
  copy:
    src: ../files/functions
    dest: ~/.dotfiles/functions

- name: Move globals into dotfiles
  copy:
    src: ../files/globals
    dest: ~/.dotfiles/globals
