- name: Check for VSCode settings
  ansible.builtin.stat:
    path: ~/Library/Application\ Support/Code/User/settings.json
  register: vscode_settings

- name: Archive Current VSCode Settings
  ansible.builtin.copy:
    src: ~/Library/Application\ Support/Code/User/settings.json
    dest: "{{ playbook_dir }}/settings.json.old"
    mode: 0644
  when: vscode_settings.stat.exists

- name: Configure VSCode Settings
  ansible.builtin.copy:
    src: ../files/settings.json
    dest: "~/Library/Application Support/Code/User/settings.json"
    mode: 0644

- name: Configure VSCode Extensions
  ansible.builtin.shell: |
    set -o pipefail
    cat roles/macbook/files/extensions.list | xargs -L1 code --install-extension
