name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup semantic-release
        run: |
          nvm install 'lts/*'
          npm i @semantic-release/changelog \
            @semantic-release/git \
            semantic-release-export-data
      - name: calculate next version
        run: npx semantic-release --dry-run
        id: next-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
